first_stage_config:
  target: ldm.models.autoencoder.AutoencoderKL
  scale_factor: 0.18215
  params:
    embed_dim: 4
    ddconfig:
      #attn_type: "vanilla-xformers"
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
